// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
    AddGenreApiV1GenresPostData,
    AddGenreApiV1GenresPostErrors,
    AddGenreApiV1GenresPostResponses,
    AddPaymentCardEndpointApiV1CardsPostData,
    AddPaymentCardEndpointApiV1CardsPostErrors,
    AddPaymentCardEndpointApiV1CardsPostResponses,
    AddSeatApiV1SeatsPostData,
    AddSeatApiV1SeatsPostErrors,
    AddSeatApiV1SeatsPostResponses,
    AddShowroomApiV1ShowroomsPostData,
    AddShowroomApiV1ShowroomsPostErrors,
    AddShowroomApiV1ShowroomsPostResponses,
    CreateMovieApiV1MoviesPostData,
    CreateMovieApiV1MoviesPostErrors,
    CreateMovieApiV1MoviesPostResponses,
    CreateShowApiV1ShowsPostData,
    CreateShowApiV1ShowsPostErrors,
    CreateShowApiV1ShowsPostResponses,
    CreateTicketApiV1TicketsPostData,
    CreateTicketApiV1TicketsPostErrors,
    CreateTicketApiV1TicketsPostResponses,
    DeleteMovieApiV1MoviesMovieIdDeleteData,
    DeleteMovieApiV1MoviesMovieIdDeleteErrors,
    DeleteMovieApiV1MoviesMovieIdDeleteResponses,
    DeletePaymentCardEndpointApiV1CardsCardIdDeleteData,
    DeletePaymentCardEndpointApiV1CardsCardIdDeleteErrors,
    DeletePaymentCardEndpointApiV1CardsCardIdDeleteResponses,
    DeleteShowApiV1ShowsShowIdDeleteData,
    DeleteShowApiV1ShowsShowIdDeleteErrors,
    DeleteShowApiV1ShowsShowIdDeleteResponses,
    DeleteTicketApiV1TicketsTicketIdDeleteData,
    DeleteTicketApiV1TicketsTicketIdDeleteErrors,
    DeleteTicketApiV1TicketsTicketIdDeleteResponses,
    GetCurrentUserProfileApiV1UsersMeGetData,
    GetCurrentUserProfileApiV1UsersMeGetResponses,
    GetGenresApiV1MoviesGenresGetData,
    GetGenresApiV1MoviesGenresGetResponses,
    GetMeApiV1MeGetData,
    GetMeApiV1MeGetResponses,
    GetMovieApiV1MoviesMovieIdGetData,
    GetMovieApiV1MoviesMovieIdGetErrors,
    GetMovieApiV1MoviesMovieIdGetResponses,
    GetPaymentCardsEndpointApiV1CardsGetData,
    GetPaymentCardsEndpointApiV1CardsGetResponses,
    GetShowByIdApiV1ShowsShowIdGetData,
    GetShowByIdApiV1ShowsShowIdGetErrors,
    GetShowByIdApiV1ShowsShowIdGetResponses,
    GetShowsByDateApiV1ShowsDateDateGetData,
    GetShowsByDateApiV1ShowsDateDateGetErrors,
    GetShowsByDateApiV1ShowsDateDateGetResponses,
    GetShowsByMovieApiV1ShowsMovieMovieIdGetData,
    GetShowsByMovieApiV1ShowsMovieMovieIdGetErrors,
    GetShowsByMovieApiV1ShowsMovieMovieIdGetResponses,
    GetTicketApiV1TicketsTicketIdGetData,
    GetTicketApiV1TicketsTicketIdGetErrors,
    GetTicketApiV1TicketsTicketIdGetResponses,
    HealthCheckHealthGetData,
    HealthCheckHealthGetResponses,
    ListMoviesApiV1MoviesGetData,
    ListMoviesApiV1MoviesGetResponses,
    ListPromosApiV1PromosGetData,
    ListPromosApiV1PromosGetResponses,
    ListShowsApiV1ShowsGetData,
    ListShowsApiV1ShowsGetResponses,
    ListTicketsApiV1TicketsGetData,
    ListTicketsApiV1TicketsGetResponses,
    PingGetData,
    PingGetResponses,
    ReadGenreApiV1GenresGenreIdGetData,
    ReadGenreApiV1GenresGenreIdGetErrors,
    ReadGenreApiV1GenresGenreIdGetResponses,
    ReadGenresApiV1GenresGetData,
    ReadGenresApiV1GenresGetResponses,
    ReadSeatApiV1SeatsSeatIdGetData,
    ReadSeatApiV1SeatsSeatIdGetErrors,
    ReadSeatApiV1SeatsSeatIdGetResponses,
    ReadSeatsApiV1SeatsGetData,
    ReadSeatsApiV1SeatsGetResponses,
    ReadShowroomApiV1ShowroomsShowroomIdGetData,
    ReadShowroomApiV1ShowroomsShowroomIdGetErrors,
    ReadShowroomApiV1ShowroomsShowroomIdGetResponses,
    ReadShowroomsApiV1ShowroomsGetData,
    ReadShowroomsApiV1ShowroomsGetResponses,
    RemoveSeatApiV1SeatsSeatIdDeleteData,
    RemoveSeatApiV1SeatsSeatIdDeleteErrors,
    RemoveSeatApiV1SeatsSeatIdDeleteResponses,
    UpdateCurrentUserProfileApiV1UsersMePutData,
    UpdateCurrentUserProfileApiV1UsersMePutErrors,
    UpdateCurrentUserProfileApiV1UsersMePutResponses,
    UpdatePaymentCardEndpointApiV1CardsCardIdPatchData,
    UpdatePaymentCardEndpointApiV1CardsCardIdPatchErrors,
    UpdatePaymentCardEndpointApiV1CardsCardIdPatchResponses,
    UpdateShowApiV1ShowsShowIdPutData,
    UpdateShowApiV1ShowsShowIdPutErrors,
    UpdateShowApiV1ShowsShowIdPutResponses
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Me
 */
export const getMeApiV1MeGet = <ThrowOnError extends boolean = false>(options?: Options<GetMeApiV1MeGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMeApiV1MeGetResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/me',
        ...options
    });
};

/**
 * Get Genres
 */
export const getGenresApiV1MoviesGenresGet = <ThrowOnError extends boolean = false>(options?: Options<GetGenresApiV1MoviesGenresGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetGenresApiV1MoviesGenresGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/movies/genres',
        ...options
    });
};

/**
 * List Movies
 */
export const listMoviesApiV1MoviesGet = <ThrowOnError extends boolean = false>(options?: Options<ListMoviesApiV1MoviesGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListMoviesApiV1MoviesGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/movies/',
        ...options
    });
};

/**
 * Create Movie
 */
export const createMovieApiV1MoviesPost = <ThrowOnError extends boolean = false>(options: Options<CreateMovieApiV1MoviesPostData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateMovieApiV1MoviesPostResponses, CreateMovieApiV1MoviesPostErrors, ThrowOnError>({
        url: '/api/v1/movies/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Movie
 */
export const deleteMovieApiV1MoviesMovieIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteMovieApiV1MoviesMovieIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteMovieApiV1MoviesMovieIdDeleteResponses, DeleteMovieApiV1MoviesMovieIdDeleteErrors, ThrowOnError>({
        url: '/api/v1/movies/{movie_id}',
        ...options
    });
};

/**
 * Get Movie
 */
export const getMovieApiV1MoviesMovieIdGet = <ThrowOnError extends boolean = false>(options: Options<GetMovieApiV1MoviesMovieIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetMovieApiV1MoviesMovieIdGetResponses, GetMovieApiV1MoviesMovieIdGetErrors, ThrowOnError>({
        url: '/api/v1/movies/{movie_id}',
        ...options
    });
};

/**
 * List Tickets
 */
export const listTicketsApiV1TicketsGet = <ThrowOnError extends boolean = false>(options?: Options<ListTicketsApiV1TicketsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListTicketsApiV1TicketsGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/tickets/',
        ...options
    });
};

/**
 * Create Ticket
 */
export const createTicketApiV1TicketsPost = <ThrowOnError extends boolean = false>(options: Options<CreateTicketApiV1TicketsPostData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateTicketApiV1TicketsPostResponses, CreateTicketApiV1TicketsPostErrors, ThrowOnError>({
        url: '/api/v1/tickets/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Ticket
 */
export const deleteTicketApiV1TicketsTicketIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteTicketApiV1TicketsTicketIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteTicketApiV1TicketsTicketIdDeleteResponses, DeleteTicketApiV1TicketsTicketIdDeleteErrors, ThrowOnError>({
        url: '/api/v1/tickets/{ticket_id}',
        ...options
    });
};

/**
 * Get Ticket
 */
export const getTicketApiV1TicketsTicketIdGet = <ThrowOnError extends boolean = false>(options: Options<GetTicketApiV1TicketsTicketIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetTicketApiV1TicketsTicketIdGetResponses, GetTicketApiV1TicketsTicketIdGetErrors, ThrowOnError>({
        url: '/api/v1/tickets/{ticket_id}',
        ...options
    });
};

/**
 * Get Current User Profile
 *
 * Return the calling user's profile.
 *
 * Uses the Supabase user id (sub claim) to query the `userprofile` table.
 */
export const getCurrentUserProfileApiV1UsersMeGet = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserProfileApiV1UsersMeGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCurrentUserProfileApiV1UsersMeGetResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/users/me',
        ...options
    });
};

/**
 * Update Current User Profile
 */
export const updateCurrentUserProfileApiV1UsersMePut = <ThrowOnError extends boolean = false>(options: Options<UpdateCurrentUserProfileApiV1UsersMePutData, ThrowOnError>) => {
    return (options.client ?? client).put<UpdateCurrentUserProfileApiV1UsersMePutResponses, UpdateCurrentUserProfileApiV1UsersMePutErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/users/me',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List Shows
 */
export const listShowsApiV1ShowsGet = <ThrowOnError extends boolean = false>(options?: Options<ListShowsApiV1ShowsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListShowsApiV1ShowsGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/shows/',
        ...options
    });
};

/**
 * Create Show
 */
export const createShowApiV1ShowsPost = <ThrowOnError extends boolean = false>(options: Options<CreateShowApiV1ShowsPostData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateShowApiV1ShowsPostResponses, CreateShowApiV1ShowsPostErrors, ThrowOnError>({
        url: '/api/v1/shows/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Show
 */
export const deleteShowApiV1ShowsShowIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteShowApiV1ShowsShowIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteShowApiV1ShowsShowIdDeleteResponses, DeleteShowApiV1ShowsShowIdDeleteErrors, ThrowOnError>({
        url: '/api/v1/shows/{show_id}',
        ...options
    });
};

/**
 * Get Show By Id
 */
export const getShowByIdApiV1ShowsShowIdGet = <ThrowOnError extends boolean = false>(options: Options<GetShowByIdApiV1ShowsShowIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetShowByIdApiV1ShowsShowIdGetResponses, GetShowByIdApiV1ShowsShowIdGetErrors, ThrowOnError>({
        url: '/api/v1/shows/{show_id}',
        ...options
    });
};

/**
 * Update Show
 */
export const updateShowApiV1ShowsShowIdPut = <ThrowOnError extends boolean = false>(options: Options<UpdateShowApiV1ShowsShowIdPutData, ThrowOnError>) => {
    return (options.client ?? client).put<UpdateShowApiV1ShowsShowIdPutResponses, UpdateShowApiV1ShowsShowIdPutErrors, ThrowOnError>({
        url: '/api/v1/shows/{show_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Shows By Movie
 */
export const getShowsByMovieApiV1ShowsMovieMovieIdGet = <ThrowOnError extends boolean = false>(options: Options<GetShowsByMovieApiV1ShowsMovieMovieIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetShowsByMovieApiV1ShowsMovieMovieIdGetResponses, GetShowsByMovieApiV1ShowsMovieMovieIdGetErrors, ThrowOnError>({
        url: '/api/v1/shows/movie/{movie_id}',
        ...options
    });
};

/**
 * Get Shows By Date
 */
export const getShowsByDateApiV1ShowsDateDateGet = <ThrowOnError extends boolean = false>(options: Options<GetShowsByDateApiV1ShowsDateDateGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetShowsByDateApiV1ShowsDateDateGetResponses, GetShowsByDateApiV1ShowsDateDateGetErrors, ThrowOnError>({
        url: '/api/v1/shows/date/{date}',
        ...options
    });
};

/**
 * Get All Showrooms
 *
 * Retrieves a list of all theater showrooms with their capacity from the database.
 */
export const readShowroomsApiV1ShowroomsGet = <ThrowOnError extends boolean = false>(options?: Options<ReadShowroomsApiV1ShowroomsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadShowroomsApiV1ShowroomsGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/showrooms',
        ...options
    });
};

/**
 * Create New Showroom
 *
 * Creates a new showroom in the database.
 *
 * - **capacity**: The maximum number of seats in the showroom (required).
 */
export const addShowroomApiV1ShowroomsPost = <ThrowOnError extends boolean = false>(options: Options<AddShowroomApiV1ShowroomsPostData, ThrowOnError>) => {
    return (options.client ?? client).post<AddShowroomApiV1ShowroomsPostResponses, AddShowroomApiV1ShowroomsPostErrors, ThrowOnError>({
        url: '/api/v1/showrooms',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Showroom by ID
 *
 * Retrieves a specific showroom by its unique ID.
 */
export const readShowroomApiV1ShowroomsShowroomIdGet = <ThrowOnError extends boolean = false>(options: Options<ReadShowroomApiV1ShowroomsShowroomIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<ReadShowroomApiV1ShowroomsShowroomIdGetResponses, ReadShowroomApiV1ShowroomsShowroomIdGetErrors, ThrowOnError>({
        url: '/api/v1/showrooms/{showroom_id}',
        ...options
    });
};

/**
 * Get All Seats
 *
 * Retrieves a list of all seats from the database.
 */
export const readSeatsApiV1SeatsGet = <ThrowOnError extends boolean = false>(options?: Options<ReadSeatsApiV1SeatsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadSeatsApiV1SeatsGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/seats',
        ...options
    });
};

/**
 * Create New Seat
 */
export const addSeatApiV1SeatsPost = <ThrowOnError extends boolean = false>(options: Options<AddSeatApiV1SeatsPostData, ThrowOnError>) => {
    return (options.client ?? client).post<AddSeatApiV1SeatsPostResponses, AddSeatApiV1SeatsPostErrors, ThrowOnError>({
        url: '/api/v1/seats',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Seat by ID
 */
export const removeSeatApiV1SeatsSeatIdDelete = <ThrowOnError extends boolean = false>(options: Options<RemoveSeatApiV1SeatsSeatIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<RemoveSeatApiV1SeatsSeatIdDeleteResponses, RemoveSeatApiV1SeatsSeatIdDeleteErrors, ThrowOnError>({
        url: '/api/v1/seats/{seat_id}',
        ...options
    });
};

/**
 * Get Seat by ID
 *
 * Retrieves a specific seat by its unique ID.
 */
export const readSeatApiV1SeatsSeatIdGet = <ThrowOnError extends boolean = false>(options: Options<ReadSeatApiV1SeatsSeatIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<ReadSeatApiV1SeatsSeatIdGetResponses, ReadSeatApiV1SeatsSeatIdGetErrors, ThrowOnError>({
        url: '/api/v1/seats/{seat_id}',
        ...options
    });
};

/**
 * Get All Genres
 *
 * Retrieves a list of all genres from the database.
 */
export const readGenresApiV1GenresGet = <ThrowOnError extends boolean = false>(options?: Options<ReadGenresApiV1GenresGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadGenresApiV1GenresGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/genres',
        ...options
    });
};

/**
 * Create New Genre
 *
 * Creates a new genre in the database.
 */
export const addGenreApiV1GenresPost = <ThrowOnError extends boolean = false>(options: Options<AddGenreApiV1GenresPostData, ThrowOnError>) => {
    return (options.client ?? client).post<AddGenreApiV1GenresPostResponses, AddGenreApiV1GenresPostErrors, ThrowOnError>({
        url: '/api/v1/genres',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Genre by ID
 *
 * Retrieves a specific genre by its unique ID.
 */
export const readGenreApiV1GenresGenreIdGet = <ThrowOnError extends boolean = false>(options: Options<ReadGenreApiV1GenresGenreIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<ReadGenreApiV1GenresGenreIdGetResponses, ReadGenreApiV1GenresGenreIdGetErrors, ThrowOnError>({
        url: '/api/v1/genres/{genre_id}',
        ...options
    });
};

/**
 * Get Payment Cards Endpoint
 */
export const getPaymentCardsEndpointApiV1CardsGet = <ThrowOnError extends boolean = false>(options?: Options<GetPaymentCardsEndpointApiV1CardsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPaymentCardsEndpointApiV1CardsGetResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/cards/',
        ...options
    });
};

/**
 * Add Payment Card Endpoint
 */
export const addPaymentCardEndpointApiV1CardsPost = <ThrowOnError extends boolean = false>(options: Options<AddPaymentCardEndpointApiV1CardsPostData, ThrowOnError>) => {
    return (options.client ?? client).post<AddPaymentCardEndpointApiV1CardsPostResponses, AddPaymentCardEndpointApiV1CardsPostErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/cards/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Payment Card Endpoint
 */
export const deletePaymentCardEndpointApiV1CardsCardIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeletePaymentCardEndpointApiV1CardsCardIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeletePaymentCardEndpointApiV1CardsCardIdDeleteResponses, DeletePaymentCardEndpointApiV1CardsCardIdDeleteErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/cards/{card_id}',
        ...options
    });
};

/**
 * Update Payment Card Endpoint
 */
export const updatePaymentCardEndpointApiV1CardsCardIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdatePaymentCardEndpointApiV1CardsCardIdPatchData, ThrowOnError>) => {
    return (options.client ?? client).patch<UpdatePaymentCardEndpointApiV1CardsCardIdPatchResponses, UpdatePaymentCardEndpointApiV1CardsCardIdPatchErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/cards/{card_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Ping
 */
export const pingGet = <ThrowOnError extends boolean = false>(options?: Options<PingGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<PingGetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};


/**
 * List Movies
 */
export const listPromosApiV1PromosGet = <ThrowOnError extends boolean = false>(options?: Options<ListPromosApiV1PromosGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListPromosApiV1PromosGetResponses, unknown, ThrowOnError>({
        url: '/api/v1/promotions/',
        ...options
    });
};