// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from "./client";
import type {
  GetGenresApiV1MoviesGenresGetData,
  GetGenresApiV1MoviesGenresGetResponses,
  ListMoviesApiV1MoviesGetData,
  ListMoviesApiV1MoviesGetResponses,
  CreateMovieApiV1MoviesPostData,
  CreateMovieApiV1MoviesPostResponses,
  CreateMovieApiV1MoviesPostErrors,
  DeleteMovieApiV1MoviesMovieIdDeleteData,
  DeleteMovieApiV1MoviesMovieIdDeleteResponses,
  DeleteMovieApiV1MoviesMovieIdDeleteErrors,
  GetMovieApiV1MoviesMovieIdGetData,
  GetMovieApiV1MoviesMovieIdGetResponses,
  GetMovieApiV1MoviesMovieIdGetErrors,
  PingGetData,
  PingGetResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
} from "./types.gen";
import { client } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get Genres
 */
export const getGenresApiV1MoviesGenresGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetGenresApiV1MoviesGenresGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetGenresApiV1MoviesGenresGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/v1/movies/genres",
    ...options,
  });
};

/**
 * List Movies
 */
export const listMoviesApiV1MoviesGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListMoviesApiV1MoviesGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ListMoviesApiV1MoviesGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/v1/movies/",
    ...options,
  });
};

/**
 * Create Movie
 */
export const createMovieApiV1MoviesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateMovieApiV1MoviesPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateMovieApiV1MoviesPostResponses,
    CreateMovieApiV1MoviesPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/movies/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Movie
 */
export const deleteMovieApiV1MoviesMovieIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteMovieApiV1MoviesMovieIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    DeleteMovieApiV1MoviesMovieIdDeleteResponses,
    DeleteMovieApiV1MoviesMovieIdDeleteErrors,
    ThrowOnError
  >({
    url: "/api/v1/movies/{movie_id}",
    ...options,
  });
};

/**
 * Get Movie
 */
export const getMovieApiV1MoviesMovieIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetMovieApiV1MoviesMovieIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetMovieApiV1MoviesMovieIdGetResponses,
    GetMovieApiV1MoviesMovieIdGetErrors,
    ThrowOnError
  >({
    url: "/api/v1/movies/{movie_id}",
    ...options,
  });
};

/**
 * Ping
 */
export const pingGet = <ThrowOnError extends boolean = false>(
  options?: Options<PingGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    PingGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/",
    ...options,
  });
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HealthCheckHealthGetResponses,
    unknown,
    ThrowOnError
  >({
    url: "/health",
    ...options,
  });
};
