// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Movie
 */
export type Movie = {
    /**
     * Title
     */
    title: string;
    /**
     * Release Date
     */
    release_date?: string;
    /**
     * Genre
     */
    genre?: string;
    /**
     * Director
     */
    director?: string;
    /**
     * Cast List
     */
    cast_list?: Array<string>;
    /**
     * Rating
     */
    rating?: number;
    /**
     * Producer
     */
    producer?: string;
    /**
     * Synopsis
     */
    synopsis?: string;
    /**
     * Reviews
     */
    reviews?: Array<string>;
    /**
     * Trailer Img
     */
    trailer_img?: string;
    /**
     * Trailer Video
     */
    trailer_video?: string;
    /**
     * Mpaa Rating
     */
    mpaa_rating?: string;
    /**
     * Show Times
     */
    show_times?: Array<string>;
    /**
     * Released
     */
    released?: boolean;
    /**
     * Movie Id
     */
    movie_id: number;
};

/**
 * MovieCreate
 */
export type MovieCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Release Date
     */
    release_date?: string;
    /**
     * Genre
     */
    genre?: string;
    /**
     * Director
     */
    director?: string;
    /**
     * Cast List
     */
    cast_list?: Array<string>;
    /**
     * Rating
     */
    rating?: number;
    /**
     * Producer
     */
    producer?: string;
    /**
     * Synopsis
     */
    synopsis?: string;
    /**
     * Reviews
     */
    reviews?: Array<string>;
    /**
     * Trailer Img
     */
    trailer_img?: string;
    /**
     * Trailer Video
     */
    trailer_video?: string;
    /**
     * Mpaa Rating
     */
    mpaa_rating?: string;
    /**
     * Show Times
     */
    show_times?: Array<string>;
    /**
     * Released
     */
    released?: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetGenresApiV1MoviesGenresGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/movies/genres';
};

export type GetGenresApiV1MoviesGenresGetResponses = {
    /**
     * Response Get Genres Api V1 Movies Genres Get
     * Successful Response
     */
    200: Array<string>;
};

export type GetGenresApiV1MoviesGenresGetResponse = GetGenresApiV1MoviesGenresGetResponses[keyof GetGenresApiV1MoviesGenresGetResponses];

export type ListMoviesApiV1MoviesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/movies/';
};

export type ListMoviesApiV1MoviesGetResponses = {
    /**
     * Response List Movies Api V1 Movies  Get
     * Successful Response
     */
    200: Array<Movie>;
};

export type ListMoviesApiV1MoviesGetResponse = ListMoviesApiV1MoviesGetResponses[keyof ListMoviesApiV1MoviesGetResponses];

export type CreateMovieApiV1MoviesPostData = {
    body: MovieCreate;
    path?: never;
    query?: never;
    url: '/api/v1/movies/';
};

export type CreateMovieApiV1MoviesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMovieApiV1MoviesPostError = CreateMovieApiV1MoviesPostErrors[keyof CreateMovieApiV1MoviesPostErrors];

export type CreateMovieApiV1MoviesPostResponses = {
    /**
     * Successful Response
     */
    200: Movie;
};

export type CreateMovieApiV1MoviesPostResponse = CreateMovieApiV1MoviesPostResponses[keyof CreateMovieApiV1MoviesPostResponses];

export type DeleteMovieApiV1MoviesMovieIdDeleteData = {
    body?: never;
    path: {
        /**
         * Movie Id
         */
        movie_id: number;
    };
    query?: never;
    url: '/api/v1/movies/{movie_id}';
};

export type DeleteMovieApiV1MoviesMovieIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMovieApiV1MoviesMovieIdDeleteError = DeleteMovieApiV1MoviesMovieIdDeleteErrors[keyof DeleteMovieApiV1MoviesMovieIdDeleteErrors];

export type DeleteMovieApiV1MoviesMovieIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMovieApiV1MoviesMovieIdGetData = {
    body?: never;
    path: {
        /**
         * Movie Id
         */
        movie_id: number;
    };
    query?: never;
    url: '/api/v1/movies/{movie_id}';
};

export type GetMovieApiV1MoviesMovieIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMovieApiV1MoviesMovieIdGetError = GetMovieApiV1MoviesMovieIdGetErrors[keyof GetMovieApiV1MoviesMovieIdGetErrors];

export type GetMovieApiV1MoviesMovieIdGetResponses = {
    /**
     * Successful Response
     */
    200: Movie;
};

export type GetMovieApiV1MoviesMovieIdGetResponse = GetMovieApiV1MoviesMovieIdGetResponses[keyof GetMovieApiV1MoviesMovieIdGetResponses];

export type PingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type PingGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};
