// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * CardDetails
 */
export type CardDetails = {
    /**
     * Name
     */
    name: string;
    /**
     * Cardnumber
     *
     * The full payment card number.
     */
    cardNumber: string;
    /**
     * Expdate
     */
    expDate: string;
    /**
     * Cvv
     */
    cvv: string;
};

/**
 * CardResponse
 */
export type CardResponse = {
    /**
     * Card Id
     */
    card_id: string;
    /**
     * Card Last Four
     */
    card_last_four: string;
    card_details: CardDetails;
    /**
     * Card Brand
     */
    card_brand: string;
    /**
     * Is Default
     */
    is_default: boolean;
};

/**
 * Genre
 */
export type Genre = {
    /**
     * Name
     */
    name: string;
    /**
     * Genre Id
     */
    genre_id: number;
};

/**
 * GenreCreate
 */
export type GenreCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Movie
 */
export type Movie = {
    /**
     * Title
     */
    title: string;
    /**
     * Release Date
     */
    release_date?: string | null;
    /**
     * Director
     */
    director?: string | null;
    /**
     * Cast List
     */
    cast_list?: Array<string> | null;
    /**
     * Rating
     */
    rating?: number | null;
    /**
     * Producer
     */
    producer?: string | null;
    /**
     * Synopsis
     */
    synopsis?: string | null;
    /**
     * Reviews
     */
    reviews?: Array<string> | null;
    /**
     * Trailer Img
     */
    trailer_img?: string | null;
    /**
     * Trailer Video
     */
    trailer_video?: string | null;
    /**
     * Mpaa Rating
     */
    mpaa_rating?: string | null;
    /**
     * Released
     */
    released?: boolean | null;
    /**
     * Featured
     */
    featured?: boolean | null;
    /**
     * Movie Id
     */
    movie_id: number;
    /**
     * Genre
     */
    genre?: Array<string> | null;
    /**
     * Show Times
     */
    show_times?: Array<string> | null;
};

/**
 * MovieCreate
 */
export type MovieCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Release Date
     */
    release_date?: string | null;
    /**
     * Director
     */
    director?: string | null;
    /**
     * Cast List
     */
    cast_list?: Array<string> | null;
    /**
     * Rating
     */
    rating?: number | null;
    /**
     * Producer
     */
    producer?: string | null;
    /**
     * Synopsis
     */
    synopsis?: string | null;
    /**
     * Reviews
     */
    reviews?: Array<string> | null;
    /**
     * Trailer Img
     */
    trailer_img?: string | null;
    /**
     * Trailer Video
     */
    trailer_video?: string | null;
    /**
     * Mpaa Rating
     */
    mpaa_rating?: string | null;
    /**
     * Released
     */
    released?: boolean | null;
    /**
     * Featured
     */
    featured?: boolean | null;
};

/**
 * NewCardRequest
 */
export type NewCardRequest = {
    details: CardDetails;
};

/**
 * Seat
 */
export type Seat = {
    /**
     * Row Letter
     */
    row_letter: string;
    /**
     * Column Number
     */
    column_number: number;
    /**
     * Showroom Id
     */
    showroom_id: number;
    /**
     * Seat Id
     */
    seat_id: number;
};

/**
 * SeatCreate
 */
export type SeatCreate = {
    /**
     * Row Letter
     */
    row_letter: string;
    /**
     * Column Number
     */
    column_number: number;
    /**
     * Showroom Id
     */
    showroom_id: number;
};

/**
 * Show
 */
export type Show = {
    /**
     * Movie Id
     */
    movie_id: number;
    /**
     * Showroom Id
     */
    showroom_id: number;
    /**
     * Date
     */
    date: string;
    /**
     * Time
     */
    time: string;
    /**
     * Show Id
     */
    show_id: number;
};

/**
 * ShowCreate
 */
export type ShowCreate = {
    /**
     * Movie Id
     */
    movie_id: number;
    /**
     * Showroom Id
     */
    showroom_id: number;
    /**
     * Date
     */
    date: string;
    /**
     * Time
     */
    time: string;
};

/**
 * ShowUpdate
 */
export type ShowUpdate = {
    /**
     * Movie Id
     */
    movie_id?: number | null;
    /**
     * Showroom Id
     */
    showroom_id?: number | null;
    /**
     * Date
     */
    date?: null;
    /**
     * Time
     */
    time?: null;
};

/**
 * Showroom
 */
export type Showroom = {
    /**
     * Capacity
     */
    capacity: number;
    /**
     * Showroom Id
     */
    showroom_id: number;
};

/**
 * ShowroomCreate
 */
export type ShowroomCreate = {
    /**
     * Capacity
     */
    capacity: number;
};

/**
 * Ticket
 */
export type Ticket = {
    /**
     * User Id
     */
    user_id?: number | null;
    /**
     * Price
     */
    price: number;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Seat Id
     */
    seat_id: number;
    /**
     * Show Id
     */
    show_id: number;
    /**
     * Ticket Id
     */
    ticket_id: number;
};

/**
 * TicketCreate
 */
export type TicketCreate = {
    /**
     * User Id
     */
    user_id?: number | null;
    /**
     * Price
     */
    price: number;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Seat Id
     */
    seat_id: number;
    /**
     * Show Id
     */
    show_id: number;
};

/**
 * UserProfileResponse
 */
export type UserProfileResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Address Line 1
     */
    address_line_1?: string | null;
    /**
     * Address Line 2
     */
    address_line_2?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Zip
     */
    zip?: string | null;
    /**
     * Country
     */
    country?: string | null;
    /**
     * Is Admin
     */
    is_admin: boolean;
    /**
     * Promotional List
     */
    promotion: boolean;
    /**
     * Phone
     */
    phone?: string | null;
};

/**
 * UserProfileUpdate
 */
export type UserProfileUpdate = {
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Address Line 1
     */
    address_line_1?: string | null;
    /**
     * Address Line 2
     */
    address_line_2?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * State
     */
    state?: string | null;
    /**
     * Zip
     */
    zip?: string | null;
    /**
     * Country
     */
    country?: string | null;
    /**
     * Promotional List
     */
    promotion?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetMeApiV1MeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type GetMeApiV1MeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetGenresApiV1MoviesGenresGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/movies/genres';
};

export type GetGenresApiV1MoviesGenresGetResponses = {
    /**
     * Response Get Genres Api V1 Movies Genres Get
     *
     * Successful Response
     */
    200: Array<string>;
};

export type GetGenresApiV1MoviesGenresGetResponse = GetGenresApiV1MoviesGenresGetResponses[keyof GetGenresApiV1MoviesGenresGetResponses];

export type ListMoviesApiV1MoviesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/movies/';
};

export type ListMoviesApiV1MoviesGetResponses = {
    /**
     * Response List Movies Api V1 Movies  Get
     *
     * Successful Response
     */
    200: Array<Movie>;
};

export type ListMoviesApiV1MoviesGetResponse = ListMoviesApiV1MoviesGetResponses[keyof ListMoviesApiV1MoviesGetResponses];

export type CreateMovieApiV1MoviesPostData = {
    body: MovieCreate;
    path?: never;
    query?: never;
    url: '/api/v1/movies/';
};

export type CreateMovieApiV1MoviesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMovieApiV1MoviesPostError = CreateMovieApiV1MoviesPostErrors[keyof CreateMovieApiV1MoviesPostErrors];

export type CreateMovieApiV1MoviesPostResponses = {
    /**
     * Successful Response
     */
    200: Movie;
};

export type CreateMovieApiV1MoviesPostResponse = CreateMovieApiV1MoviesPostResponses[keyof CreateMovieApiV1MoviesPostResponses];

export type DeleteMovieApiV1MoviesMovieIdDeleteData = {
    body?: never;
    path: {
        /**
         * Movie Id
         */
        movie_id: number;
    };
    query?: never;
    url: '/api/v1/movies/{movie_id}';
};

export type DeleteMovieApiV1MoviesMovieIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMovieApiV1MoviesMovieIdDeleteError = DeleteMovieApiV1MoviesMovieIdDeleteErrors[keyof DeleteMovieApiV1MoviesMovieIdDeleteErrors];

export type DeleteMovieApiV1MoviesMovieIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteMovieApiV1MoviesMovieIdDeleteResponse = DeleteMovieApiV1MoviesMovieIdDeleteResponses[keyof DeleteMovieApiV1MoviesMovieIdDeleteResponses];

export type GetMovieApiV1MoviesMovieIdGetData = {
    body?: never;
    path: {
        /**
         * Movie Id
         */
        movie_id: number;
    };
    query?: never;
    url: '/api/v1/movies/{movie_id}';
};

export type GetMovieApiV1MoviesMovieIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMovieApiV1MoviesMovieIdGetError = GetMovieApiV1MoviesMovieIdGetErrors[keyof GetMovieApiV1MoviesMovieIdGetErrors];

export type GetMovieApiV1MoviesMovieIdGetResponses = {
    /**
     * Successful Response
     */
    200: Movie;
};

export type GetMovieApiV1MoviesMovieIdGetResponse = GetMovieApiV1MoviesMovieIdGetResponses[keyof GetMovieApiV1MoviesMovieIdGetResponses];

export type ListTicketsApiV1TicketsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tickets/';
};

export type ListTicketsApiV1TicketsGetResponses = {
    /**
     * Response List Tickets Api V1 Tickets  Get
     *
     * Successful Response
     */
    200: Array<Ticket>;
};

export type ListTicketsApiV1TicketsGetResponse = ListTicketsApiV1TicketsGetResponses[keyof ListTicketsApiV1TicketsGetResponses];

export type CreateTicketApiV1TicketsPostData = {
    body: TicketCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tickets/';
};

export type CreateTicketApiV1TicketsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTicketApiV1TicketsPostError = CreateTicketApiV1TicketsPostErrors[keyof CreateTicketApiV1TicketsPostErrors];

export type CreateTicketApiV1TicketsPostResponses = {
    /**
     * Successful Response
     */
    200: Ticket;
};

export type CreateTicketApiV1TicketsPostResponse = CreateTicketApiV1TicketsPostResponses[keyof CreateTicketApiV1TicketsPostResponses];

export type DeleteTicketApiV1TicketsTicketIdDeleteData = {
    body?: never;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: number;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}';
};

export type DeleteTicketApiV1TicketsTicketIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTicketApiV1TicketsTicketIdDeleteError = DeleteTicketApiV1TicketsTicketIdDeleteErrors[keyof DeleteTicketApiV1TicketsTicketIdDeleteErrors];

export type DeleteTicketApiV1TicketsTicketIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTicketApiV1TicketsTicketIdGetData = {
    body?: never;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: number;
    };
    query?: never;
    url: '/api/v1/tickets/{ticket_id}';
};

export type GetTicketApiV1TicketsTicketIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTicketApiV1TicketsTicketIdGetError = GetTicketApiV1TicketsTicketIdGetErrors[keyof GetTicketApiV1TicketsTicketIdGetErrors];

export type GetTicketApiV1TicketsTicketIdGetResponses = {
    /**
     * Successful Response
     */
    200: Ticket;
};

export type GetTicketApiV1TicketsTicketIdGetResponse = GetTicketApiV1TicketsTicketIdGetResponses[keyof GetTicketApiV1TicketsTicketIdGetResponses];

export type GetCurrentUserProfileApiV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetCurrentUserProfileApiV1UsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserProfileResponse;
};

export type GetCurrentUserProfileApiV1UsersMeGetResponse = GetCurrentUserProfileApiV1UsersMeGetResponses[keyof GetCurrentUserProfileApiV1UsersMeGetResponses];

export type UpdateCurrentUserProfileApiV1UsersMePutData = {
    body: UserProfileUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateCurrentUserProfileApiV1UsersMePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCurrentUserProfileApiV1UsersMePutError = UpdateCurrentUserProfileApiV1UsersMePutErrors[keyof UpdateCurrentUserProfileApiV1UsersMePutErrors];

export type UpdateCurrentUserProfileApiV1UsersMePutResponses = {
    /**
     * Successful Response
     */
    200: UserProfileResponse;
};

export type UpdateCurrentUserProfileApiV1UsersMePutResponse = UpdateCurrentUserProfileApiV1UsersMePutResponses[keyof UpdateCurrentUserProfileApiV1UsersMePutResponses];

export type ListShowsApiV1ShowsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/shows/';
};

export type ListShowsApiV1ShowsGetResponses = {
    /**
     * Response List Shows Api V1 Shows  Get
     *
     * Successful Response
     */
    200: Array<Show>;
};

export type ListShowsApiV1ShowsGetResponse = ListShowsApiV1ShowsGetResponses[keyof ListShowsApiV1ShowsGetResponses];

export type CreateShowApiV1ShowsPostData = {
    body: ShowCreate;
    path?: never;
    query?: never;
    url: '/api/v1/shows/';
};

export type CreateShowApiV1ShowsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateShowApiV1ShowsPostError = CreateShowApiV1ShowsPostErrors[keyof CreateShowApiV1ShowsPostErrors];

export type CreateShowApiV1ShowsPostResponses = {
    /**
     * Successful Response
     */
    200: Show;
};

export type CreateShowApiV1ShowsPostResponse = CreateShowApiV1ShowsPostResponses[keyof CreateShowApiV1ShowsPostResponses];

export type DeleteShowApiV1ShowsShowIdDeleteData = {
    body?: never;
    path: {
        /**
         * Show Id
         */
        show_id: number;
    };
    query?: never;
    url: '/api/v1/shows/{show_id}';
};

export type DeleteShowApiV1ShowsShowIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteShowApiV1ShowsShowIdDeleteError = DeleteShowApiV1ShowsShowIdDeleteErrors[keyof DeleteShowApiV1ShowsShowIdDeleteErrors];

export type DeleteShowApiV1ShowsShowIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetShowByIdApiV1ShowsShowIdGetData = {
    body?: never;
    path: {
        /**
         * Show Id
         */
        show_id: number;
    };
    query?: never;
    url: '/api/v1/shows/{show_id}';
};

export type GetShowByIdApiV1ShowsShowIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetShowByIdApiV1ShowsShowIdGetError = GetShowByIdApiV1ShowsShowIdGetErrors[keyof GetShowByIdApiV1ShowsShowIdGetErrors];

export type GetShowByIdApiV1ShowsShowIdGetResponses = {
    /**
     * Successful Response
     */
    200: Show;
};

export type GetShowByIdApiV1ShowsShowIdGetResponse = GetShowByIdApiV1ShowsShowIdGetResponses[keyof GetShowByIdApiV1ShowsShowIdGetResponses];

export type UpdateShowApiV1ShowsShowIdPutData = {
    body: ShowUpdate;
    path: {
        /**
         * Show Id
         */
        show_id: number;
    };
    query?: never;
    url: '/api/v1/shows/{show_id}';
};

export type UpdateShowApiV1ShowsShowIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateShowApiV1ShowsShowIdPutError = UpdateShowApiV1ShowsShowIdPutErrors[keyof UpdateShowApiV1ShowsShowIdPutErrors];

export type UpdateShowApiV1ShowsShowIdPutResponses = {
    /**
     * Successful Response
     */
    200: Show;
};

export type UpdateShowApiV1ShowsShowIdPutResponse = UpdateShowApiV1ShowsShowIdPutResponses[keyof UpdateShowApiV1ShowsShowIdPutResponses];

export type GetShowsByMovieApiV1ShowsMovieMovieIdGetData = {
    body?: never;
    path: {
        /**
         * Movie Id
         */
        movie_id: number;
    };
    query?: never;
    url: '/api/v1/shows/movie/{movie_id}';
};

export type GetShowsByMovieApiV1ShowsMovieMovieIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetShowsByMovieApiV1ShowsMovieMovieIdGetError = GetShowsByMovieApiV1ShowsMovieMovieIdGetErrors[keyof GetShowsByMovieApiV1ShowsMovieMovieIdGetErrors];

export type GetShowsByMovieApiV1ShowsMovieMovieIdGetResponses = {
    /**
     * Response Get Shows By Movie Api V1 Shows Movie  Movie Id  Get
     *
     * Successful Response
     */
    200: Array<Show>;
};

export type GetShowsByMovieApiV1ShowsMovieMovieIdGetResponse = GetShowsByMovieApiV1ShowsMovieMovieIdGetResponses[keyof GetShowsByMovieApiV1ShowsMovieMovieIdGetResponses];

export type GetShowsByDateApiV1ShowsDateDateGetData = {
    body?: never;
    path: {
        /**
         * Date
         */
        date: string;
    };
    query?: never;
    url: '/api/v1/shows/date/{date}';
};

export type GetShowsByDateApiV1ShowsDateDateGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetShowsByDateApiV1ShowsDateDateGetError = GetShowsByDateApiV1ShowsDateDateGetErrors[keyof GetShowsByDateApiV1ShowsDateDateGetErrors];

export type GetShowsByDateApiV1ShowsDateDateGetResponses = {
    /**
     * Response Get Shows By Date Api V1 Shows Date  Date  Get
     *
     * Successful Response
     */
    200: Array<Show>;
};

export type GetShowsByDateApiV1ShowsDateDateGetResponse = GetShowsByDateApiV1ShowsDateDateGetResponses[keyof GetShowsByDateApiV1ShowsDateDateGetResponses];

export type ReadShowroomsApiV1ShowroomsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/showrooms';
};

export type ReadShowroomsApiV1ShowroomsGetResponses = {
    /**
     * Response Read Showrooms Api V1 Showrooms Get
     *
     * Successful Response
     */
    200: Array<Showroom>;
};

export type ReadShowroomsApiV1ShowroomsGetResponse = ReadShowroomsApiV1ShowroomsGetResponses[keyof ReadShowroomsApiV1ShowroomsGetResponses];

export type AddShowroomApiV1ShowroomsPostData = {
    body: ShowroomCreate;
    path?: never;
    query?: never;
    url: '/api/v1/showrooms';
};

export type AddShowroomApiV1ShowroomsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddShowroomApiV1ShowroomsPostError = AddShowroomApiV1ShowroomsPostErrors[keyof AddShowroomApiV1ShowroomsPostErrors];

export type AddShowroomApiV1ShowroomsPostResponses = {
    /**
     * Successful Response
     */
    201: Showroom;
};

export type AddShowroomApiV1ShowroomsPostResponse = AddShowroomApiV1ShowroomsPostResponses[keyof AddShowroomApiV1ShowroomsPostResponses];

export type ReadShowroomApiV1ShowroomsShowroomIdGetData = {
    body?: never;
    path: {
        /**
         * Showroom Id
         */
        showroom_id: number;
    };
    query?: never;
    url: '/api/v1/showrooms/{showroom_id}';
};

export type ReadShowroomApiV1ShowroomsShowroomIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadShowroomApiV1ShowroomsShowroomIdGetError = ReadShowroomApiV1ShowroomsShowroomIdGetErrors[keyof ReadShowroomApiV1ShowroomsShowroomIdGetErrors];

export type ReadShowroomApiV1ShowroomsShowroomIdGetResponses = {
    /**
     * Successful Response
     */
    200: Showroom;
};

export type ReadShowroomApiV1ShowroomsShowroomIdGetResponse = ReadShowroomApiV1ShowroomsShowroomIdGetResponses[keyof ReadShowroomApiV1ShowroomsShowroomIdGetResponses];

export type ReadSeatsApiV1SeatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/seats';
};

export type ReadSeatsApiV1SeatsGetResponses = {
    /**
     * Response Read Seats Api V1 Seats Get
     *
     * Successful Response
     */
    200: Array<Seat>;
};

export type ReadSeatsApiV1SeatsGetResponse = ReadSeatsApiV1SeatsGetResponses[keyof ReadSeatsApiV1SeatsGetResponses];

export type AddSeatApiV1SeatsPostData = {
    body: SeatCreate;
    path?: never;
    query?: never;
    url: '/api/v1/seats';
};

export type AddSeatApiV1SeatsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddSeatApiV1SeatsPostError = AddSeatApiV1SeatsPostErrors[keyof AddSeatApiV1SeatsPostErrors];

export type AddSeatApiV1SeatsPostResponses = {
    /**
     * Successful Response
     */
    201: Seat;
};

export type AddSeatApiV1SeatsPostResponse = AddSeatApiV1SeatsPostResponses[keyof AddSeatApiV1SeatsPostResponses];

export type RemoveSeatApiV1SeatsSeatIdDeleteData = {
    body?: never;
    path: {
        /**
         * Seat Id
         */
        seat_id: number;
    };
    query?: never;
    url: '/api/v1/seats/{seat_id}';
};

export type RemoveSeatApiV1SeatsSeatIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveSeatApiV1SeatsSeatIdDeleteError = RemoveSeatApiV1SeatsSeatIdDeleteErrors[keyof RemoveSeatApiV1SeatsSeatIdDeleteErrors];

export type RemoveSeatApiV1SeatsSeatIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveSeatApiV1SeatsSeatIdDeleteResponse = RemoveSeatApiV1SeatsSeatIdDeleteResponses[keyof RemoveSeatApiV1SeatsSeatIdDeleteResponses];

export type ReadSeatApiV1SeatsSeatIdGetData = {
    body?: never;
    path: {
        /**
         * Seat Id
         */
        seat_id: number;
    };
    query?: never;
    url: '/api/v1/seats/{seat_id}';
};

export type ReadSeatApiV1SeatsSeatIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadSeatApiV1SeatsSeatIdGetError = ReadSeatApiV1SeatsSeatIdGetErrors[keyof ReadSeatApiV1SeatsSeatIdGetErrors];

export type ReadSeatApiV1SeatsSeatIdGetResponses = {
    /**
     * Successful Response
     */
    200: Seat;
};

export type ReadSeatApiV1SeatsSeatIdGetResponse = ReadSeatApiV1SeatsSeatIdGetResponses[keyof ReadSeatApiV1SeatsSeatIdGetResponses];

export type ReadGenresApiV1GenresGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/genres';
};

export type ReadGenresApiV1GenresGetResponses = {
    /**
     * Response Read Genres Api V1 Genres Get
     *
     * Successful Response
     */
    200: Array<Genre>;
};

export type ReadGenresApiV1GenresGetResponse = ReadGenresApiV1GenresGetResponses[keyof ReadGenresApiV1GenresGetResponses];

export type AddGenreApiV1GenresPostData = {
    body: GenreCreate;
    path?: never;
    query?: never;
    url: '/api/v1/genres';
};

export type AddGenreApiV1GenresPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddGenreApiV1GenresPostError = AddGenreApiV1GenresPostErrors[keyof AddGenreApiV1GenresPostErrors];

export type AddGenreApiV1GenresPostResponses = {
    /**
     * Successful Response
     */
    201: Genre;
};

export type AddGenreApiV1GenresPostResponse = AddGenreApiV1GenresPostResponses[keyof AddGenreApiV1GenresPostResponses];

export type ReadGenreApiV1GenresGenreIdGetData = {
    body?: never;
    path: {
        /**
         * Genre Id
         */
        genre_id: number;
    };
    query?: never;
    url: '/api/v1/genres/{genre_id}';
};

export type ReadGenreApiV1GenresGenreIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadGenreApiV1GenresGenreIdGetError = ReadGenreApiV1GenresGenreIdGetErrors[keyof ReadGenreApiV1GenresGenreIdGetErrors];

export type ReadGenreApiV1GenresGenreIdGetResponses = {
    /**
     * Successful Response
     */
    200: Genre;
};

export type ReadGenreApiV1GenresGenreIdGetResponse = ReadGenreApiV1GenresGenreIdGetResponses[keyof ReadGenreApiV1GenresGenreIdGetResponses];

export type GetPaymentCardsEndpointApiV1CardsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/cards/';
};

export type GetPaymentCardsEndpointApiV1CardsGetResponses = {
    /**
     * Response Get Payment Cards Endpoint Api V1 Cards  Get
     *
     * Successful Response
     */
    200: Array<CardResponse>;
};

export type GetPaymentCardsEndpointApiV1CardsGetResponse = GetPaymentCardsEndpointApiV1CardsGetResponses[keyof GetPaymentCardsEndpointApiV1CardsGetResponses];

export type AddPaymentCardEndpointApiV1CardsPostData = {
    body: NewCardRequest;
    path?: never;
    query?: never;
    url: '/api/v1/cards/';
};

export type AddPaymentCardEndpointApiV1CardsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddPaymentCardEndpointApiV1CardsPostError = AddPaymentCardEndpointApiV1CardsPostErrors[keyof AddPaymentCardEndpointApiV1CardsPostErrors];

export type AddPaymentCardEndpointApiV1CardsPostResponses = {
    /**
     * Response Add Payment Card Endpoint Api V1 Cards  Post
     *
     * Successful Response
     */
    201: Array<CardResponse>;
};

export type AddPaymentCardEndpointApiV1CardsPostResponse = AddPaymentCardEndpointApiV1CardsPostResponses[keyof AddPaymentCardEndpointApiV1CardsPostResponses];

export type DeletePaymentCardEndpointApiV1CardsCardIdDeleteData = {
    body?: never;
    path: {
        /**
         * Card Id
         */
        card_id: string;
    };
    query?: never;
    url: '/api/v1/cards/{card_id}';
};

export type DeletePaymentCardEndpointApiV1CardsCardIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePaymentCardEndpointApiV1CardsCardIdDeleteError = DeletePaymentCardEndpointApiV1CardsCardIdDeleteErrors[keyof DeletePaymentCardEndpointApiV1CardsCardIdDeleteErrors];

export type DeletePaymentCardEndpointApiV1CardsCardIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePaymentCardEndpointApiV1CardsCardIdDeleteResponse = DeletePaymentCardEndpointApiV1CardsCardIdDeleteResponses[keyof DeletePaymentCardEndpointApiV1CardsCardIdDeleteResponses];

export type UpdatePaymentCardEndpointApiV1CardsCardIdPatchData = {
    body: NewCardRequest;
    path: {
        /**
         * Card Id
         */
        card_id: string;
    };
    query?: never;
    url: '/api/v1/cards/{card_id}';
};

export type UpdatePaymentCardEndpointApiV1CardsCardIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePaymentCardEndpointApiV1CardsCardIdPatchError = UpdatePaymentCardEndpointApiV1CardsCardIdPatchErrors[keyof UpdatePaymentCardEndpointApiV1CardsCardIdPatchErrors];

export type UpdatePaymentCardEndpointApiV1CardsCardIdPatchResponses = {
    /**
     * Successful Response
     */
    200: CardResponse;
};

export type UpdatePaymentCardEndpointApiV1CardsCardIdPatchResponse = UpdatePaymentCardEndpointApiV1CardsCardIdPatchResponses[keyof UpdatePaymentCardEndpointApiV1CardsCardIdPatchResponses];

export type PingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type PingGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
