CREATE OR REPLACE TABLE movie (
    movie_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    release_date DATE,
    genre TEXT,
    director TEXT,
    cast TEXT[],
    rating DECIMAL,
    producer TEXT,
    synopsis TEXT,
    reviews TEXT[],
    trailer_img TEXT,
    trailer_video TEXT,
    MPAA_rating DECIMAL,
    ts.show_times TIMESTAMP[],
    released BOOLEAN DEFAULT FALSE,
    JOIN theater_sections ON movie.id = theater_sections.movie_id ts,
    JOIN theaters ON theater.movie_id = movie.id

)